apiVersion: v1
kind: Service
metadata:
    name: "libreonlinecluster-f0fa"
    labels:
        app: "libreonlinecluster-f0fa"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "libreonlinecluster-f0fa"